[workspace]

[package]
edition = "2024"
name = "fibewi-esp-bootloader"
rust-version = "1.88"
version = "0.1.0"
license = "MIT"
description = "FiBeWI second-stage A/B bootloader for ESP32-C3"

[[bin]]
name = "fibewi-esp-bootloader"
path = "src/main.rs"

[features]
default = []
esp32c3 = ["esp-hal/esp32c3", "esp-println/esp32c3", "espbewi-boot/esp32c3"]
esp32s3 = ["esp-hal/esp32s3", "esp-println/esp32s3", "espbewi-boot/esp32s3"]

[dependencies]
esp-hal = { version = "~1.1.0" }
esp-println = { version = "0.17.0" }
fibewi-esp = { path = "../../backends/esp" }
espbewi-boot = { git = "https://github.com/iobewi/espbewi", rev = "bda59c8bec995fe3fdceb52dd3fb3a1744708961", package = "espbewi-boot", default-features = false }
espbewi-platform = { git = "https://github.com/iobewi/espbewi", rev = "bda59c8bec995fe3fdceb52dd3fb3a1744708961", package = "espbewi-platform" }

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "s"
panic = "abort"
debug = 2
overflow-checks = false
